name: 🐞 Issue report
description: Report an issue in Anikku
labels: [bug]
body:
  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to reproduce
      description: Provide an example of the issue.
      placeholder: |
        Example:
          1. First step
          2. Second step
          3. Issue here
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Explain what you should expect to happen.
      placeholder: |
        Example:
          "This should happen..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: Explain what actually happens.
      placeholder: |
        Example:
          "This happened instead..."
    validations:
      required: true

  - type: textarea
    id: crash-logs
    attributes:
      label: Crash logs
      description: |
        If you're experiencing crashes, if possible, go to the app's **More → Settings → Advanced** page, press **Dump crash logs** and share the crash logs here.
      placeholder: |
        You can upload the crash log file as an attachment, or paste the crash logs in plain text if needed.

  - type: input
    id: anikku-version
    attributes:
      label: Anikku version
      description: You can find your Anikku version in **More → About**.
      placeholder: |
        Example: "0.1.2"
    validations:
      required: true

  - type: input
    id: android-version
    attributes:
      label: Android version
      description: You can find this somewhere in your Android settings.
      placeholder: |
        Example: "Android 11"
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device
      description: List your device and model.
      placeholder: |
        Example: "Google Pixel 5"
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: Other details
      placeholder: |
        Additional details and attachments.

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Read this carefully, we will close and ignore your issue if you skimmed through this.
      options:
        - label: I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
          required: true
        - label: I have written a short but informative title.
          required: true
        - label: I have gone through the [FAQ](https://anikku-app.github.io/docs/faq/general) and [troubleshooting guide](https://anikku-app.github.io/docs/guides/troubleshooting/).
          required: true
        - label: I have updated the app to **[latest version](https://github.com/komikku-app/anikku/releases/latest)**.
          required: true
        - label: I have filled out all of the requested information in this form, including specific version numbers.
          required: true
        - label: I understand that **Anikku does not have or fix any extensions**, and I **will not receive help** for any issues related to sources or extensions.
          required: true

  - type: "textarea"
    id: "prioritisation"
    attributes:
      label: "Is this issue important to you?"
      description: |
        **Please do not modify this text area!**

        This template let users to vote with a :+1: reaction if they find it important.
        This is not a guarantee that highly-requested issues will be fixed first, but it helps us to figure out what's important to users. Please react on other users' issues if you find them important.
      value: |
        Add a :+1: [reaction] to [issues you find important].

        [reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
        [issues you find important]: https://github.com/komikku-app/anikku/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
